name: Build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install "jupyterlab>=4,<5"
          YARN_ENABLE_IMMUTABLE_INSTALLS=false jlpm install

      - name: Lint the extension
        run: jlpm lint:check

      - name: Build and install the extension
        run: |
          set -eux
          jlpm build:prod
          python -m pip install .

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyter_mset_theme.*OK"
          python -m jupyterlab.browser_check --no-chrome-test

      - name: Package the extension
        run: |
          set -eux
          python -m build
          python -m pip uninstall -y "jupyter_mset_theme" jupyterlab

      - name: Upload extension packages
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts
          path: dist/jupyter_mset_theme*
          if-no-files-found: error

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-artifacts

      - name: Install and test wheel
        run: |
          set -eux
          python -m pip install --upgrade pip
          python -m pip install "jupyterlab>=4,<5" jupyter_mset_theme*.whl

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyter_mset_theme.*OK"
          python -m jupyterlab.browser_check --no-chrome-test


  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
